### ISSUE TITLE
面板不能更改端口映射吗？

### ISSUE THREAD

**Issue by YJSxLD** [Mr-Leaves-Server-Group/Manual#45]
我从某服务商那里购买的面板服务器，七日杀的，但是在网络端口那里我无法更改，是我没有权限还是要这里就不能更改呢？（七日杀的默认端口和服务商提供的不同）

**Comment by KenRen98** [comment]
可以的啊，联系开服的供应商，他们可以给您切端口的。启动指令那里，直接override掉了端口了。

`
./7DaysToDieServer.x86_64 -configfile=serverconfig.xml -quit -batchmode -nographics -dedicated -ServerPort=${SERVER_PORT} -ServerDisabledNetworkProtocols=${SERVER_DISABLED_NETWORK_PROTOCOLS} -ServerMaxPlayerCount=${MAX_PLAYERS} -GameDifficulty=${GAME_DIFFICULTY} -ControlPanelEnabled=false -TelnetEnabled=true -TelnetPort=${TELNET_PORT} -TelnetPassword=${PASSWORD} -logfile logs/latest.log & echo -e "Checking on telnet connection" && until nc -z -v -w5 127.0.0.1 ${TELNET_PORT}; do echo "Waiting for telnet connection..."; sleep 5; done && $( [[ -z ${PASSWORD} ]] && printf %s "telnet -E 127.0.0.1 ${TELNET_PORT}" || printf %s "rcon -t telnet -a 127.0.0.1:${TELNET_PORT} -p {{PASSWORD}}" )
`
